'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase'
import type { Room } from '@/types/database'

export default function ManageRooms(){const supabase=createClient();const [rooms,setRooms]=useState<Room[]>([]);const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('')
useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data}=await supabase.from('rooms').select('*').order('room_number');setRooms((data??[]) as Room[]);setLoading(false)})()},[])
async function toggle(r:Room){setMsg('Menyimpan...');const next=r.availability==='Tersedia'?'Terisi':'Tersedia';const {data,error}=await supabase.from('rooms').update({availability:next}).eq('id',r.id).select().single();if(error)setMsg(error.message);else{setRooms(rs=>rs.map(x=>x.id===r.id?data as Room:x));setMsg('Status tersimpan ✓')}}
async function remove(r:Room){if(!confirm(`Hapus Kamar ${r.room_number}?`))return;const {error}=await supabase.from('rooms').delete().eq('id',r.id);if(error)setMsg(error.message);else{setRooms(rs=>rs.filter(x=>x.id!==r.id));setMsg('Kamar berhasil dihapus ✓')}}
return <main className="min-h-screen bg-[#fffaf5] px-6 py-8 md:px-12"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><Link href="/admin" className="text-sm text-black/50 hover:text-black">← Dashboard</Link><h1 className="mt-3 text-3xl font-bold">Kelola Kamar</h1><p className="mt-1 text-sm text-black/50">Atur harga, status, foto, fasilitas, dan informasi setiap kamar.</p></div><Link href="/admin/kamar/tambah" className="inline-flex items-center justify-center rounded-full bg-amber-300 px-5 py-3 font-bold text-black shadow-sm transition hover:bg-amber-400">+ Tambah Kamar</Link></div>{msg&&<p className="mt-5 rounded-xl border bg-white px-4 py-3 text-sm">{msg}</p>}{loading?<p className="mt-8">Memuat...</p>:rooms.length===0?<div className="mt-8 rounded-3xl border bg-white p-10 text-center"><p className="text-lg font-bold">Belum ada kamar</p><p className="mt-2 text-sm text-black/50">Tambahkan kamar pertama untuk mulai mengelola kos.</p></div>:<div className="mt-8 grid gap-4">{rooms.map(r=><div key={r.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex items-center gap-3"><p className="text-xl font-bold">{r.room_number}</p><span className={`rounded-full px-3 py-1 text-xs font-bold ${r.availability==='Tersedia'?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>{r.availability}</span></div><p className="mt-2 font-semibold">Rp {Number(r.price).toLocaleString('id-ID')} / bulan</p><p className="mt-1 line-clamp-2 text-sm text-black/50">{r.description}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>toggle(r)} className="rounded-full border px-4 py-2 text-sm font-semibold hover:bg-black/5">{r.availability==='Tersedia'?'Tandai Terisi':'Tandai Tersedia'}</button><Link href={`/admin/kamar/${r.id}`} className="rounded-full bg-black px-4 py-2 text-sm font-semibold text-white hover:bg-black/80">Edit</Link><button onClick={()=>remove(r)} className="rounded-full border border-red-200 px-4 py-2 text-sm font-semibold text-red-600 hover:bg-red-50">Hapus</button></div></div></div>)}</div>}</div></main>}
