'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase'
import type { Room } from '@/types/database'

export default function AdminPage(){const supabase=createClient();const router=useRouter();const [rooms,setRooms]=useState<Room[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:profile}=await supabase.from('admin_profiles').select('role').eq('user_id',user.id).maybeSingle();if(profile?.role!=='owner'){await supabase.auth.signOut();router.replace('/login');return}const {data,error}=await supabase.from('rooms').select('*').order('room_number');if(error)setError(error.message);else setRooms((data??[]) as Room[]);setLoading(false)})()},[])
async function logout(){await supabase.auth.signOut();router.replace('/login');router.refresh()}
return <main className="min-h-screen px-6 py-8 md:px-12"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] opacity-50">Owner Area</p><h1 className="mt-1 text-3xl font-bold">Dashboard Kos Bu Nori</h1></div><button onClick={logout} className="rounded-full border px-4 py-2 text-sm font-semibold">Keluar</button></header><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-3xl border bg-white p-6"><p className="text-sm opacity-60">Total kamar</p><p className="mt-2 text-3xl font-bold">{rooms.length}</p></div><div className="rounded-3xl border bg-white p-6"><p className="text-sm opacity-60">Tersedia</p><p className="mt-2 text-3xl font-bold">{rooms.filter(r=>r.availability==='Tersedia').length}</p></div><div className="rounded-3xl border bg-white p-6"><p className="text-sm opacity-60">Terisi</p><p className="mt-2 text-3xl font-bold">{rooms.filter(r=>r.availability==='Terisi').length}</p></div></div><div className="mt-8 flex items-center justify-between"><h2 className="text-xl font-bold">Daftar kamar</h2><Link href="/admin/kamar" className="rounded-full bg-black px-5 py-3 text-sm font-semibold text-white">Kelola Kamar</Link></div>{loading?<p className="mt-6 opacity-60">Memuat...</p>:error?<p className="mt-6 text-red-600">{error}</p>:<div className="mt-4 overflow-hidden rounded-3xl border bg-white"><div className="divide-y">{rooms.map(r=><div key={r.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-bold">Kamar {r.room_number}</p><p className="text-sm opacity-60">Rp {Number(r.price).toLocaleString('id-ID')} / bulan</p></div><span className="rounded-full bg-black/5 px-3 py-1 text-xs">{r.availability}</span></div>)}</div></div>}</div></main>}
