'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase'

export default function AddRoom(){const router=useRouter();const supabase=createClient();const [roomNumber,setRoomNumber]=useState('');const [price,setPrice]=useState('1000000');const [availability,setAvailability]=useState<'Tersedia'|'Terisi'>('Tersedia');const [facilities,setFacilities]=useState('');const [description,setDescription]=useState('Kamar kos nyaman dan bersih');const [saving,setSaving]=useState(false);const [msg,setMsg]=useState('')
useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)router.replace('/login')})()},[])
async function save(e:FormEvent){e.preventDefault();if(!roomNumber.trim()){setMsg('Nomor kamar wajib diisi.');return}setSaving(true);setMsg('');const {data,error}=await supabase.from('rooms').insert({room_number:roomNumber.trim(),price:Number(price)||0,availability,facilities:facilities.trim()||null,description:description.trim()||'Kamar kos nyaman dan bersih',image_url:null}).select('id').single();if(error){setMsg(error.code==='23505'?'Nomor kamar tersebut sudah digunakan.':error.message);setSaving(false);return}router.push(`/admin/kamar/${data.id}`)}
return <main className="min-h-screen bg-[#fffaf5] px-6 py-8 md:px-12"><div className="mx-auto max-w-2xl"><Link href="/admin/kamar" className="text-sm text-black/50 hover:text-black">← Kembali</Link><h1 className="mt-4 text-3xl font-bold">Tambah Kamar</h1><p className="mt-1 text-sm text-black/50">Isi informasi dasar kamar. Setelah dibuat, kamu bisa langsung menambahkan fotonya.</p><form onSubmit={save} className="mt-8 space-y-5 rounded-3xl border bg-white p-6 shadow-sm"><label className="block text-sm font-semibold">Nomor Kamar<input value={roomNumber} onChange={e=>setRoomNumber(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-black" placeholder="Kamar 8"/></label><label className="block text-sm font-semibold">Harga / bulan<input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-black"/></label><label className="block text-sm font-semibold">Status<select value={availability} onChange={e=>setAvailability(e.target.value as 'Tersedia'|'Terisi')} className="mt-2 w-full rounded-xl border px-4 py-3"><option>Tersedia</option><option>Terisi</option></select></label><label className="block text-sm font-semibold">Fasilitas<input value={facilities} onChange={e=>setFacilities(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="Kasur, lemari, WiFi, kamar mandi"/><span className="mt-1 block text-xs text-black/40">Pisahkan dengan koma.</span></label><label className="block text-sm font-semibold">Deskripsi<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5} className="mt-2 w-full rounded-xl border px-4 py-3"/></label>{msg&&<p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{msg}</p>}<button disabled={saving} className="w-full rounded-xl bg-amber-300 px-5 py-3 font-bold text-black shadow-sm hover:bg-amber-400 disabled:opacity-50">{saving?'Membuat Kamar...':'Buat Kamar'}</button></form></div></main>}
