'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase'
import type { Room } from '@/types/database'

export default function EditRoom({params}:{params:Promise<{id:string}>}){const router=useRouter();const supabase=createClient();const [id,setId]=useState('');const [room,setRoom]=useState<Room|null>(null);const [saving,setSaving]=useState(false);const [msg,setMsg]=useState('');
useEffect(()=>{params.then(p=>{setId(p.id);(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data}=await supabase.from('rooms').select('*').eq('id',Number(p.id)).single();setRoom(data as Room)})()})},[])
async function save(e:FormEvent){e.preventDefault();if(!room)return;setSaving(true);setMsg('');const {error}=await supabase.from('rooms').update({room_number:room.room_number,price:room.price,availability:room.availability,description:room.description,facilities:room.facilities,image_url:room.image_url}).eq('id',room.id);if(error)setMsg(error.message);else{setMsg('Data kamar berhasil disimpan ✓');router.refresh()}setSaving(false)}
if(!room)return <main className="p-8">Memuat...</main>;return <main className="min-h-screen px-6 py-8 md:px-12"><div className="mx-auto max-w-2xl"><Link href="/admin/kamar" className="text-sm opacity-60">← Kembali</Link><h1 className="mt-4 text-3xl font-bold">Edit Kamar {room.room_number}</h1><form onSubmit={save} className="mt-8 space-y-5 rounded-3xl border bg-white p-6"><label className="block text-sm font-semibold">Nomor Kamar<input value={room.room_number} onChange={e=>setRoom({...room,room_number:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-semibold">Harga / bulan<input type="number" value={room.price} onChange={e=>setRoom({...room,price:Number(e.target.value)})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-semibold">Status<select value={room.availability} onChange={e=>setRoom({...room,availability:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"><option>Tersedia</option><option>Terisi</option></select></label><label className="block text-sm font-semibold">Fasilitas<input value={room.facilities??''} onChange={e=>setRoom({...room,facilities:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="Kasur, lemari, WiFi, kamar mandi"/><span className="mt-1 block text-xs opacity-50">Pisahkan dengan koma.</span></label><label className="block text-sm font-semibold">Deskripsi<textarea value={room.description} onChange={e=>setRoom({...room,description:e.target.value})} rows={5} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-semibold">URL Foto<input value={room.image_url??''} onChange={e=>setRoom({...room,image_url:e.target.value||null})} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="https://..."/><span className="mt-1 block text-xs opacity-50">Upload foto langsung akan kita tambahkan setelah Storage disiapkan.</span></label>{msg&&<p className="text-sm">{msg}</p>}<button disabled={saving} className="w-full rounded-xl bg-black px-5 py-3 font-semibold text-white">{saving?'Menyimpan...':'Simpan Perubahan'}</button></form></div></main>}
