'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase'
import type { Room } from '@/types/database'

export default function EditRoom({params}:{params:Promise<{id:string}>}){const router=useRouter();const supabase=createClient();const [room,setRoom]=useState<Room|null>(null);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [msg,setMsg]=useState('');
useEffect(()=>{params.then(async p=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data,error}=await supabase.from('rooms').select('*').eq('id',Number(p.id)).single();if(error||!data){setMsg('Kamar tidak ditemukan.');return}setRoom(data as Room)})},[])
async function uploadImage(file:File){if(!room)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMsg('Format foto harus JPG, PNG, atau WebP.');return}if(file.size>5*1024*1024){setMsg('Ukuran foto maksimal 5 MB.');return}setUploading(true);setMsg('Mengupload foto...');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`room-${room.id}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('room-images').upload(path,file,{contentType:file.type,upsert:true});if(error){setMsg(`Upload gagal: ${error.message}`);setUploading(false);return}const {data}=supabase.storage.from('room-images').getPublicUrl(path);setRoom({...room,image_url:data.publicUrl});setMsg('Foto berhasil diupload. Jangan lupa simpan perubahan.');setUploading(false)}
async function save(e:FormEvent){e.preventDefault();if(!room)return;setSaving(true);setMsg('');const {error}=await supabase.from('rooms').update({room_number:room.room_number,price:room.price,availability:room.availability,description:room.description,facilities:room.facilities,image_url:room.image_url}).eq('id',room.id);if(error)setMsg(error.message);else{setMsg('Data kamar berhasil disimpan ✓');router.refresh()}setSaving(false)}
if(!room)return <main className="p-8">{msg||'Memuat...'}</main>;return <main className="min-h-screen px-6 py-8 md:px-12"><div className="mx-auto max-w-2xl"><Link href="/admin/kamar" className="text-sm opacity-60">← Kembali</Link><h1 className="mt-4 text-3xl font-bold">Edit Kamar {room.room_number}</h1><form onSubmit={save} className="mt-8 space-y-5 rounded-3xl border bg-white p-6"><div><p className="text-sm font-semibold">Foto Kamar</p>{room.image_url?<img src={room.image_url} alt={`Kamar ${room.room_number}`} className="mt-3 aspect-[4/3] w-full rounded-2xl object-cover"/>:<div className="mt-3 flex aspect-[4/3] items-center justify-center rounded-2xl bg-black/5 text-6xl">🏠</div>}<label className="mt-3 block cursor-pointer rounded-xl border px-4 py-3 text-center font-semibold">{uploading?'Mengupload...':'Pilih Foto dari Perangkat'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)uploadImage(f)}} className="hidden"/></label><p className="mt-2 text-xs opacity-50">JPG, PNG, WebP • maksimal 5 MB</p></div><label className="block text-sm font-semibold">Nomor Kamar<input value={room.room_number} onChange={e=>setRoom({...room,room_number:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-semibold">Harga / bulan<input type="number" value={room.price} onChange={e=>setRoom({...room,price:Number(e.target.value)})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-semibold">Status<select value={room.availability} onChange={e=>setRoom({...room,availability:e.target.value as Room['availability']})} className="mt-2 w-full rounded-xl border px-4 py-3"><option>Tersedia</option><option>Terisi</option></select></label><label className="block text-sm font-semibold">Fasilitas<input value={room.facilities??''} onChange={e=>setRoom({...room,facilities:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="Kasur, lemari, WiFi, kamar mandi"/><span className="mt-1 block text-xs opacity-50">Pisahkan dengan koma.</span></label><label className="block text-sm font-semibold">Deskripsi<textarea value={room.description} onChange={e=>setRoom({...room,description:e.target.value})} rows={5} className="mt-2 w-full rounded-xl border px-4 py-3"/></label>{msg&&<p className="rounded-xl bg-black/5 px-4 py-3 text-sm">{msg}</p>}<button disabled={saving||uploading} className="w-full rounded-xl bg-black px-5 py-3 font-semibold text-white disabled:opacity-50">{saving?'Menyimpan...':'Simpan Perubahan'}</button></form></div></main>}
